version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
  django:
    container_name: django
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env