version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - .env

  django:
    container_name: django
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./backend:/app

  javascript:
    container_name: javascript
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - django
    env_file:
      - .env
    volumes:
      - ./frontend:/app

  prometheus:
    image: prom/prometheus:latest
    container_name:  prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./setup/prometheus:/setup/prometheus
      - prometheus-data:/prometheus
    command:
      - "--config.file=/setup/prometheus/prometheus.yml"
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - 9187:9187
    depends_on:
      - postgres
    env_file:
      - .env

  elasticsearch: # single node cluster

    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
    volumes:
      - ./setup/elasticsearch:/setup/elasticsearch
      - elastic-data:/usr/share/elasticsearch/data/
    # command: /bin/sh ./setup/elasticsearch/elasticsearch.sh

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: logstash
    ports:
      - '9600:9600'
    depends_on:
      - elasticsearch
    env_file:
      - .env
    volumes:
      - ./setup/logstash:/setup/logstash
    command: logstash -f /setup/logstash/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    env_file:
      - .env


volumes:

  prometheus-data:
    driver: local

  grafana-data:
    driver: local

  elastic-data:
    driver: local