# Generated by Django 4.2.9 on 2024-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('base', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='user',
			name='display_name',
			field=models.CharField(blank=True, max_length=20),
		),
		migrations.AddField(
			model_name='user',
			name='email',
			field=models.EmailField(blank=True, max_length=100),
		),
		migrations.AlterField(
			model_name='user',
			name='username',
			field=models.CharField(max_length=20),
		),
	]

