# Generated by Django 4.2.9 on 2024-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='player_1_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='player_2_id',
            field=models.CharField(max_length=20),
        ),
    ]
