# Generated by Django 4.2.9 on 2024-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_matchup_player_1_id_alter_matchup_player_2_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='versus',
            name='game_mode',
            field=models.CharField(default='game_mode', max_length=20),
        ),
    ]
