# Generated by Django 4.2.9 on 2024-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_data_is_visible_versus_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versus',
            name='game_mode',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
