# Generated by Django 4.2.9 on 2024-03-23 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_tournament_player_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='placements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
    ]
