global:
  scrape_interval: 15s

rule_files:
  - '/setup/prometheus/postgres_down.rules'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
